### ISSUE TITLE
我看了下bootstrap,发现使用的是3,为什么风格还是2得风格,我认为3默认的风格会更好一些

### ISSUE THREAD

**Issue by wuliriki** [wuwx/MultiTenantCMS#2]
ok,我看到css 用了一个theme,但是为何不尝试下flat ui或其他的,这个ui并不是很舒服

**Comment by wuwx** [comment]
那我把先把那个 theme 删除掉，让他保持默认 bootstrap3 的风格
我准备通过多 theme 的支持的方式引入 flat-ui，然后在后台可以选择使用哪种风格

**Comment by wuliriki** [comment]
https://github.com/FezVrasta/bootstrap-material-design
考虑用下这个 相当不错的UI

**Comment by wuwx** [comment]
增加对 flat-ui 的支持了~~~~

**Comment by wuliriki** [comment]
yeah good

**Comment by wuwx** [comment]
现在使用 themes_on_rails 添加了一下
感觉还有不少代码需要美化的空间
可以慢慢继续弄了~~
至少有个目标

**Comment by wuliriki** [comment]
yes,有需要的话，我可以提供一些代码

**Comment by wuwx** [comment]
欢迎欢迎的呀

**Comment by wuliriki** [comment]
我会的不是特别多，最主要的是家里的网很是无语，有时候github打不开

**Comment by wuwx** [comment]
多提供一些期待的功能和建议对我也是极大的帮助哇

**Comment by wuliriki** [comment]
ok
